name: unit-test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4

      - name: Find changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            loggingx:
              - "loggingx/**"

      - name: Set up Python
        if: steps.filter.outputs.loggingx == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies with poetry
        if: steps.filter.outputs.loggingx == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        if: steps.filter.outputs.loggingx == 'true'
        run: |
          poetry run pytest
